//
//  RegistersProtocols.swift
//  Test_ios
//
//  Created udom on 20/6/2562 BE.
//  Copyright © 2562 udom Neakaew. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol RegistersWireframeProtocol: class {

}
//MARK: Presenter -
protocol RegistersPresenterProtocol: class {
    func confirmSuccess()
}

//MARK: Interactor -
protocol RegistersInteractorProtocol: class {

  var presenter: RegistersPresenterProtocol?  { get set }
}

//MARK: View -
protocol RegistersViewProtocol: class {

  var presenter: RegistersPresenterProtocol?  { get set }
}
