//
//  RegistersInteractor.swift
//  Test_ios
//
//  Created udom on 20/6/2562 BE.
//  Copyright © 2562 udom Neakaew. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RegistersInteractor: RegistersInteractorProtocol {

    weak var presenter: RegistersPresenterProtocol?
}
