//
//  DashboardProtocols.swift
//  Test_ios
//
//  Created udom on 20/6/2562 BE.
//  Copyright © 2562 udom Neakaew. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol DashboardWireframeProtocol: class {

}
//MARK: Presenter -
protocol DashboardPresenterProtocol: class {

}

//MARK: Interactor -
protocol DashboardInteractorProtocol: class {

  var presenter: DashboardPresenterProtocol?  { get set }
}

//MARK: View -
protocol DashboardViewProtocol: class {

  var presenter: DashboardPresenterProtocol?  { get set }
}
